/* autogenerated by pidl */

/* DO NOT EDIT
	This filter was automatically generated
	from wzcsvc.idl and wzcsvc.cnf.
	
	Pidl is a perl based IDL compiler for DCE/RPC idl files.
	It is maintained by the Samba team, not the Wireshark team.
	Instructions on how to download and install Pidl can be
	found at http://wiki.wireshark.org/Pidl

	$Id: packet-dcerpc-wzcsvc.h 53122 2013-11-06 22:55:17Z jmayer $
*/


#ifndef __PACKET_DCERPC_WZCSVC_H
#define __PACKET_DCERPC_WZCSVC_H

#endif /* __PACKET_DCERPC_WZCSVC_H */
